spring.application.name=cocktail-be
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%X{requestId:-      -}] %clr(%-5level) --- %clr(%logger{36}){cyan} : %msg%n
spring.profiles.active=local
# Database Configuration - local 프로필로 재정의해야 함. (환경변수 대용)
#spring.datasource.url=XXXX
#spring.datasource.username=XXXX
#spring.datasource.password=XXXX
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

api.flavor-resolver.url=http://localhost:8000/predict
api.openrouter.url=XXXX
api.openrouter.key=XXXX
api.openrouter.model=XXXX
