spring.application.name=cocktail-be
spring.profiles.active=local
# Database Configuration - local 프로필로 재정의해야 함. (환경변수 대용)
#spring.datasource.url=XXXX
#spring.datasource.username=XXXX
#spring.datasource.password=XXXX
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

api.flavor-resolver.url=http://localhost:8000/predict
api.gemini.url=XXXX
api.gemini.key=XXXX
